config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sessions/new'
  

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  root 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :campaigns

  
  

end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  has_attached_file :photo, :styles => { :medium => "600x400>", :thumb => "300x200>" }, :default_url => "background3.jpg"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true, length: { maximum: 150 }
  validates :description, presence: true
  validates :story, presence: true
  validates :target_date, presence: true
  validates :goal, presence: true

  belongs_to :user

  rails_admin do
    list do
      field :id
      field :title
      field :description
      field :story
      field :target_date
      field :goal
      field :photo
    end
  end
end

app/models/donation.rb
class Donation < ActiveRecord::Base
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  # devise :database_authenticatable, :registerable,
  #      :recoverable, :rememberable, :trackable, :validatable
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :address, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }, length: { maximum: 50 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :campaigns


end

app/controllers/application_controller.rb
WEBSITE_NAME="Pax Kapital"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def index
  	# render text: "Hello, world"
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all
  end

  def new
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'

      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @recent_campaigns = Campaign.last(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to #{WEBSITE_NAME}"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :last_name, :email, :address, :password,
                                   :password_confirmation)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_controller_helper.rb
module CampaignsControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/campaigns/_campaign_card.html.erb
<div class="col l4 s12">
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag campaign.photo.url(:thumb) %>
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><%= link_to campaign.title, campaign %> <i class="mdi-navigation-more-vert right"></i></span>
      <p><a href="#">Campaign Goal: <%= campaign.goal %></a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><%= link_to campaign.title, campaign %> <i class="mdi-navigation-close right"></i></span>
      <p><%= campaign.story %></p>
    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="container">
  <div class="section">
    <div class="row">
      <%= render partial: 'campaigns/campaign_card', collection: @campaigns, :as => :campaign %>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<div id="campaign-view-parallax" class="parallax-container">
  <div class="parallax"><%= image_tag @campaign.photo.url %></div>
</div>
<div class="container">
  <div class="section">
    <div class="row">
      <div class="col m8 s12">
        <p class="flow-text">
        <strong><%= @campaign.title %></strong>
        <h6><a class="modal-trigger waves-effect waves-light btn-large" href="#modal1">Invest</a></h6>
        </p>
      </div>
      <div class="col m4 s12"><p class="flow-text">
        <strong>Goal: <h3><%= number_to_currency @campaign.goal %></h3></p></strong>
      </div>
    </div>
    <h6>What we're working towards:</h6>
    <p class="flow-text"><%= @campaign.description %></p>
    <h6>What we're all about:</h6>
    <p class="flow-text"><%= @campaign.story %></p>
  </div>
</div>
<div id="modal1" class="modal">
  <%= form_tag("/stripe") do %>
  <div class="modal-content">
    <div class="input-field col s12 m6">
      <label for="name">First Name</label>
      <%= text_field :name, class: "validate" %>
    </div>
    <div class="input-field col s12 m6">
      
      <%= text_field :last_name, class: "validate" %>
    </div>
    <div class="input-field col s12 m6">
      
      <%= text_field :address, class: "validate" %>
    </div> 
    <div class="input-field col s12 m6">
      
      <%= email_field :email, class: "validate" %>
    </div>
  </div>
  <div class="modal-footer">
    <%= submit_tag "Purchase Kapital", class: "btn" %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Pax Kapital</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar-fixed">
  <nav class="white" role="navigation">
    <% if logged_in? %>
      <ul id="dropdown1" class="dropdown-content">
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
    <% end %>
    <div class="nav-wrapper container">
      <a id="logo-container" href="/" class="brand-logo"> Pax</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">How It Works</a></li>
        <li><%= link_to "Campaigns", campaigns_path %></li>
        <% if logged_in? %>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.name %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <% else %>
          <li><a href="/signup">Login/Register</a></li>
        <% end %>
      </ul>
      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">How It Works</a></li>
        <li><%= link_to "Campaigns", campaigns_path %></li>
        <li><a href="/signup">Login/Register</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
</div>
<% flash.each do |message_type, message| %>
  <script>
    Materialize.toast("<%= "#{message}" %>", 5000)
  </script>
<% end %>

<%= yield %>

<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4"></p>


      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <%= debug(params) if Rails.env.development? %>
</footer>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center teal-text text-lighten-2">Find Your Place</h1>
      <div class="row center">
        <h5 class="header col s12 light">Help build your neighborhood</h5>
      </div>
      <div class="row center">
        <%= link_to "Active Campaigns", campaigns_path, class: "btn-large waves-effect waves-light teal lighten-1", id: "download-button" %>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><img src="/background3.jpg" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
  <div class="section">
    Recent
    <div class="row">
        <%= render partial: 'campaigns/campaign_card', collection: @recent_campaigns, :as => :campaign %>
    </div>
  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">Fund your project today</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="map.png" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">

      <div class="col s6">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="mdi-image-flash-on"></i></h2>
          <h5 class="center">Locals</h5>

          <p class="light">Are you a Charleston local? Find a campaign today and get involved.</p>
        </div>
      </div>


      <div class="col s6">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="mdi-social-group"></i></h2>
          <h5 class="center">Businesses</h5>

          <p class="light">Are you a business looking to start a campaign for your neighborhood and raise money? Sign up today.</p>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light"></h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="background3.jpg" alt="Unsplashed background img 3"></div>
</div>

<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Contact Us</h4>
        <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
      </div>
    </div>

  </div>
</div>


  <!--  Scripts-->

app/views/users/new.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center teal-text text-lighten-2">Registration</h1>
      <div class="row center">
        <h5 class="header col s12 light">Just a few questions before we get started...</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="http://lorempixel.com/1400/800/nature/5/" alt="Unsplashed background img 2"></div>
</div>
<div class="container">
  <div class="section">
    <div class="row">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="input-field col s12 m6">
          <%= f.label :name %>
          <%= f.text_field :name, class: "validate" %>
        </div>
        <div class="input-field col s12 m6">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "validate" %>
        </div>
        <div class="input-field col s12 m6">
          <%= f.label :address %>
          <%= f.text_field :address, class: "validate" %>
        </div> 
        <div class="input-field col s12 m6">
          <%= f.label :email %>
          <%= f.email_field :email, class: "validate" %>
        </div>
        <div class="input-field col s12 m6">
          <%= f.label :password %>
          <%= f.password_field :password, class: "validate" %>
        </div>
        <div class="input-field col s12 m6">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: "validate" %>
        </div>
        <div class="col s12">
          <div class="row">
            <%= f.submit "Create my account", class: "btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="section">
    <% provide(:title, @user.name) %>
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </div>
</div>